version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Clearing npm cache...
    - npm cache clean --force
    - echo Installing source NPM dependencies...
    - npm install --force
  build:
    commands:
      - echo Build started on 'date'
      - npm run build

artifacts:
  files:
    - '**/*'
    #- "build/**/*"
  base-directory: 'build'
  #discard-paths: yes
